added a bunch of mocks

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,25 +1,3 @@
-# Licensed to the Apache Software Foundation (ASF) under one
-# or more contributor license agreements.  See the NOTICE file
-# distributed with this work for additional information
-# regarding copyright ownership.  The ASF licenses this file
-# to you under the Apache License, Version 2.0 (the
-# "License"); you may not use this file except in compliance
-# with the License.  You may obtain a copy of the License at
-#
-#   http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing,
-# software distributed under the License is distributed on an
-# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-# KIND, either express or implied.  See the License for the
-# specific language governing permissions and limitations
-# under the License.
-#
-
-# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
-#
-# WARNING: This configuration is for local development. Do not use it in a production deployment.
-#
 # This configuration supports basic configuration using environment variables or an .env file
 # The following variables are supported:
 #
@@ -41,8 +19,7 @@
 #                                A better way is to build a custom image or extend the official image
 #                                as described in https://airflow.apache.org/docs/docker-stack/build.html.
 #                                Default: ''
-#
-# Feel free to modify this file to suit your needs.
+
 ---
 version: '3.8'
 x-airflow-common:
@@ -56,25 +33,26 @@ x-airflow-common:
     &airflow-common-env
     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
-    # For backward compatibility, with Airflow <2.3
     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
     AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
     AIRFLOW__CORE__FERNET_KEY: ''
     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
     AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+    AIRFLOW__CORE__TEST_CONNECTION: Enabled
     AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
-    # yamllint disable rule:line-length
-    # Use simple http server on scheduler for health checks
-    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
-    # yamllint enable rule:line-length
     AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
+    AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS: 'true'
     # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
     # for other purpose (development, test and especially production usage) build/extend Airflow image.
     _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
   volumes:
     - ${AIRFLOW_PROJ_DIR:-.}/spork:/opt/spork
+    - ${AIRFLOW_PROJ_DIR:-.}/bin:/opt/bin
+    - ${AIRFLOW_PROJ_DIR:-.}/drivers:/opt/drivers
     - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
+    - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
+    - ${AIRFLOW_PROJ_DIR:-.}/files:/opt/airflow/files
     - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
     - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
     - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
@@ -118,7 +96,7 @@ services:
     <<: *airflow-common
     command: webserver
     ports:
-      - "8085:8080"
+      - "8080:8080"
     healthcheck:
       test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
       interval: 30s
@@ -167,7 +145,7 @@ services:
       <<: *airflow-common-depends-on
       airflow-init:
         condition: service_completed_successfully
-
+    
   airflow-triggerer:
     <<: *airflow-common
     command: triggerer
@@ -197,13 +175,13 @@ services:
         airflow_version_comparable=$$(ver $${airflow_version})
         min_airflow_version=2.2.0
         min_airflow_version_comparable=$$(ver $${min_airflow_version})
-        if (( airflow_version_comparable < min_airflow_version_comparable )); then
-          echo
-          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
-          echo
-          exit 1
-        fi
+        # if (( airflow_version_comparable < min_airflow_version_comparable )); then
+        #   echo
+        #   echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+        #   echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+        #   echo
+        #   exit 1
+        # fi
         if [[ -z "${AIRFLOW_UID}" ]]; then
           echo
           echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
@@ -277,6 +255,7 @@ services:
   # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
   # or by explicitly targeted on the command line e.g. docker-compose up flower.
   # See: https://docs.docker.com/compose/profiles/
+
   flower:
     <<: *airflow-common
     command: celery flower
@@ -296,5 +275,337 @@ services:
       airflow-init:
         condition: service_completed_successfully
 
+# =================================================================================
+# ||                               ELASTICSEARCH                                 ||
+# =================================================================================
+
+  # elasticsearch:
+  #   image: elasticsearch:7.5.2
+  #   container_name: elasticsearch
+  #   environment:
+  #     - discovery.type=single-node
+  #   ports:
+  #     - 9200:9200
+  #     - 9300:9300
+
+# =================================================================================
+# ||                                CASSANDRA                                    ||
+# =================================================================================
+
+  # cassandra_1:
+  #   image: cassandra:latest
+  #   container_name: cassandra_1
+  #   environment:
+  #     - CASSANDRA_SEEDS=cassandra_1
+  #   volumes:
+  #     - cassandra-1:/var/lib/cassandra
+
+  #  cassandra_2:
+  #    image: cassandra:latest
+  #    container_name: cassandra_2
+  #    environment:
+  #      - CASSANDRA_SEEDS=cassandra_1
+  #    volumes:
+  #      - cassandra-2:/var/lib/cassandra
+
+# =================================================================================
+# ||                                  SCYLLA                                     ||
+# =================================================================================
+
+  # scylla_1:
+  #   image: scylladb/scylla
+  #   container_name: scylla_1
+  #   ports:
+  #     - 9042:9042
+  #   command:
+  #     - --seeds=scylla_1
+  #     - --smp 2
+  #   volumes:
+  #     - scylla-1:/var/lib/scylla
+
+  # scylla_2:
+  #   image: scylladb/scylla
+  #   container_name: scylla_2
+  #   command: 
+  #     - --seeds=scylla_1
+  #     - --smp 2
+  #   volumes:
+  #     - scylla-2:/var/lib/scylla
+
+  # scylla_3:
+  #   image: scylladb/scylla
+  #   container_name: scylla_3
+  #   command: 
+  #     - --seeds=scylla_1
+  #     - --smp 2
+  #   volumes:
+  #     - scylla-3:/var/lib/scylla
+
+# =================================================================================
+# ||                                 KAFKA                                       ||
+# =================================================================================
+
+  # zookeeper:
+  #   image: confluentinc/cp-zookeeper
+  #   container_name: zookeeper
+  #   environment:
+  #     ZOOKEEPER_CLIENT_PORT: 2181
+  #     ZOOKEEPER_TICK_TIME: 2000
+  #   ports:
+  #     - 22181:2181
+
+  # kafka1:
+  #   image: confluentinc/cp-kafka:7.3.2
+  #   container_name: kafka1
+  #   ports:
+  #     - "9092:9092"
+  #     - "29092:29092"
+  #   depends_on:
+  #     - zookeeper
+  #   environment:
+  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
+  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
+  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
+  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
+  #     KAFKA_BROKER_ID: 1
+  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
+  #     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
+  #     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
+
+  # kafka2:
+  #   image: confluentinc/cp-kafka:7.3.2
+  #   container_name: kafka2
+  #   ports:
+  #     - "9093:9093"
+  #     - "29093:29093"
+  #   depends_on:
+  #     - zookeeper
+  #   environment:
+  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29093,EXTERNAL://localhost:9093
+  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
+  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
+  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
+  #     KAFKA_BROKER_ID: 2
+  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
+  #     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
+  #     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
+
+  # kafka3:
+  #   image: confluentinc/cp-kafka:7.3.2
+  #   container_name: kafka3
+  #   ports:
+  #     - "9094:9094"
+  #     - "29094:29094"
+  #   depends_on:
+  #     - zookeeper
+  #   environment:
+  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29094,EXTERNAL://localhost:9094
+  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
+  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
+  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
+  #     KAFKA_BROKER_ID: 3
+  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
+  #     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
+  #     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
+
+# =================================================================================
+# ||                              HIVE STANDALONE                                ||
+# =================================================================================
+
+ #  metastore:
+ #    image: apache/hive:3.1.3
+ #    container_name: metastore-standalone
+ #    environment:
+ #      - SERVICE_NAME=metastore
+ #    healthcheck:
+ #      test: curl --fail http://localhost:9083 || exit 1
+ #      interval: 60s
+ #      retries: 5
+ #      start_period: 20s
+ #      timeout: 10s
+ #    ports:
+ #      - 9083:9083
+ #    volumes:
+ #      - hive_warehouse:/opt/hive/data/warehouse
+
+ #  hive:
+ #    image: apache/hive:3.1.3
+ #    container_name: hive-standalone
+ #    environment:
+ #      - SERVICE_NAME=hiveserver2
+ #      - SERVICE_OPTS="-Dhive.metastore.uris=thrift://metastore-standalone:9083"
+ #      - IS_RESUME="true"
+ #    ports:
+ #      - 10000:10000
+ #      - 10002:10002
+ #    volumes:
+ #      - hive_warehouse:/opt/hive/data/warehouse
+ #    restart: always
+ #    depends_on:
+ #      metastore:
+ #        condition: service_started
+
+ 
+
+# =================================================================================
+# ||                                  HADOOP                                     ||
+# =================================================================================
+
+  # namenode:
+  #   image: apache/hadoop:3
+  #   hostname: namenode
+  #   command: ["hdfs", "namenode"]
+  #   ports:
+  #     - 9870:9870
+  #   env_file:
+  #     - ./config
+  #   environment:
+  #     ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
+  # datanode:
+  #   image: apache/hadoop:3
+  #   command: ["hdfs", "datanode"]
+  #   env_file:
+  #     - ./config      
+  # resourcemanager:
+  #   image: apache/hadoop:3
+  #   hostname: resourcemanager
+  #   command: ["yarn", "resourcemanager"]
+  #   ports:
+  #     - 8088:8088
+  #   env_file:
+  #     - ./config
+  #   volumes:
+  #     - ./test.sh:/opt/test.sh
+  # nodemanager:
+  #   image: apache/hadoop:3
+  #   command: ["yarn", "nodemanager"]
+  #   env_file:
+  #     - ./config
+
+
+# =================================================================================
+# ||                              SPARK HADOOP                                   ||
+# =================================================================================
+
+  # spark-master:
+  #   image: apache/spark
+  #   container_name: spark-master
+  #   command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
+  #   restart: always
+  #   ports:
+  #     - 7077:7077
+  #     - 8090:8088
+  #   volumes:
+  #     - ./spork:/opt/app
+
+  # spark-worker1:
+  #   image: apache/spark
+  #   container_name: spark-worker1
+  #   command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
+  #   restart: always
+  #   volumes:
+  #     - ./spork:/opt/app
+
+  # resourcemanager:
+  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
+  #   container_name: resourcemanager
+  #   restart: always
+  #   environment:
+  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
+  #   env_file:
+  #     - ./hadoop.env
+
+  # nodemanager1:
+  #   image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
+  #   container_name: nodemanager
+  #   restart: always
+  #   environment:
+  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
+  #   env_file:
+  #     - ./hadoop.env
+
+  # historyserver:
+  #   image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
+  #   container_name: historyserver
+  #   restart: always
+  #   environment:
+  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
+  #   volumes:
+  #     - hadoop_historyserver:/hadoop/yarn/timeline
+  #   env_file:
+  #     - ./hadoop.env
+
+  # spark-master:
+  #   image: bde2020/spark-master:3.0.0-hadoop3.2
+  #   container_name: spark-master
+  #   depends_on:
+  #     - namenode
+  #     - datanode
+  #   ports:
+  #     - "8080:8080"
+  #     - "7077:7077"
+  #   environment:
+  #     - INIT_DAEMON_STEP=setup_spark
+  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
+  #   volumes:
+  #     - ./spork:/opt/app
+  #     - ./drivers:/opt/drivers
+
+  # spark-worker-1:
+  #   image: bde2020/spark-worker:3.0.0-hadoop3.2
+  #   container_name: spark-worker-1
+  #   depends_on:
+  #     - spark-master
+  #   ports:
+  #     - "8081:8081"
+  #   environment:
+  #     - "SPARK_MASTER=spark://spark-master:7077"
+  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
+
+  # hive-server:
+  #   image: bde2020/hive:2.3.2-postgresql-metastore
+  #   container_name: hive-server
+  #   depends_on:
+  #     - namenode
+  #     - datanode
+  #   env_file:
+  #     - ./hadoop-hive.env
+  #   environment:
+  #     HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
+  #     SERVICE_PRECONDITION: "hive-metastore:9083"
+  #   ports:
+  #     - "10005:10000"
+
+  # hive-metastore:
+  #   image: bde2020/hive:2.3.2-postgresql-metastore
+  #   container_name: hive-metastore
+  #   env_file:
+  #     - ./hadoop-hive.env
+  #   command: /opt/hive/bin/hive --service metastore
+  #   environment:
+  #     SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
+  #   ports:
+  #     - "9083:9083"
+
+  # hive-metastore-postgresql:
+  #   image: bde2020/hive-metastore-postgresql:2.3.0
+  #   container_name: hive-metastore-postgresql
+
+  # presto-coordinator:
+  #   image: shawnzhu/prestodb:0.181
+  #   container_name: presto-coordinator
+  #   ports:
+  #     - "8089:8089"
+
 volumes:
+  # hadoop_namenode:
+  # hadoop_datanode:
+  # hadoop_historyserver:
+  # hive_warehouse:
   postgres-db-volume:
+  # scylla-1:
+  # scylla-2:
+  # scylla-3:
+  # cassandra-1:
+  # cassandra-2:
+
